/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;
import dominio.*;

/**
 *
 * @author seba2
 */
public class variosReportes extends javax.swing.JFrame {

    /**
     * Creates new form variosReportes
     */
    public variosReportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radiosHistorial = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabHistorial = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaVehiculos = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        ordenarFecha = new javax.swing.JButton();
        radioSalidas = new javax.swing.JRadioButton();
        radioServicios = new javax.swing.JRadioButton();
        radioEntradas = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tabMovimientos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        tabEstadisticas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaClientesContratos = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaEmpleadosMovs = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        listaServiciosMasUtilizados = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelEstadia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTabbedPane1.setBorder(new javax.swing.border.MatteBorder(null));

        tabHistorial.setLayout(null);

        jScrollPane2.setViewportView(listaVehiculos);

        tabHistorial.add(jScrollPane2);
        jScrollPane2.setBounds(90, 50, 100, 190);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Movimientos");
        tabHistorial.add(jLabel3);
        jLabel3.setBounds(260, 20, 100, 20);

        ordenarFecha.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        ordenarFecha.setText("Ordenar por fecha");
        ordenarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenarFechaActionPerformed(evt);
            }
        });
        tabHistorial.add(ordenarFecha);
        ordenarFecha.setBounds(560, 50, 140, 23);

        radiosHistorial.add(radioSalidas);
        radioSalidas.setText("Salidas");
        tabHistorial.add(radioSalidas);
        radioSalidas.setBounds(570, 110, 98, 21);

        radiosHistorial.add(radioServicios);
        radioServicios.setText("Servicio adicional");
        tabHistorial.add(radioServicios);
        radioServicios.setBounds(570, 160, 120, 21);

        radiosHistorial.add(radioEntradas);
        radioEntradas.setText("Entradas");
        radioEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEntradasActionPerformed(evt);
            }
        });
        tabHistorial.add(radioEntradas);
        radioEntradas.setBounds(570, 130, 80, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Vehiculo");
        tabHistorial.add(jLabel4);
        jLabel4.setBounds(100, 20, 100, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable1);

        tabHistorial.add(jScrollPane6);
        jScrollPane6.setBounds(230, 50, 310, 190);

        jLabel1.setText("<Orden tabla>");
        tabHistorial.add(jLabel1);
        jLabel1.setBounds(560, 80, 140, 16);

        jTabbedPane1.addTab("Historial", tabHistorial);

        tabMovimientos.setLayout(null);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "<Fecha actual>", "<Fecha +1>", "<Fecha +2>"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        tabMovimientos.add(jScrollPane3);
        jScrollPane3.setBounds(220, 0, 452, 260);

        jTabbedPane1.addTab("Movimientos", tabMovimientos);

        tabEstadisticas.setLayout(null);

        jScrollPane1.setViewportView(listaClientesContratos);

        tabEstadisticas.add(jScrollPane1);
        jScrollPane1.setBounds(500, 60, 170, 130);

        jScrollPane4.setViewportView(listaEmpleadosMovs);

        tabEstadisticas.add(jScrollPane4);
        jScrollPane4.setBounds(260, 60, 170, 130);

        jScrollPane5.setViewportView(listaServiciosMasUtilizados);

        tabEstadisticas.add(jScrollPane5);
        jScrollPane5.setBounds(20, 60, 170, 130);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Servicios más utilizados");
        tabEstadisticas.add(jLabel5);
        jLabel5.setBounds(20, 30, 170, 20);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Clientes con más contratos");
        tabEstadisticas.add(jLabel6);
        jLabel6.setBounds(500, 30, 200, 20);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Empleados con menos movimientos");
        tabEstadisticas.add(jLabel7);
        jLabel7.setBounds(220, 30, 260, 20);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Estadia más larga: ");
        tabEstadisticas.add(jLabel2);
        jLabel2.setBounds(30, 230, 140, 20);

        labelEstadia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tabEstadisticas.add(labelEstadia);
        labelEstadia.setBounds(160, 230, 170, 0);

        jTabbedPane1.addTab("Estadisticas generales", tabEstadisticas);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(40, 40, 770, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ordenarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenarFechaActionPerformed
        
    }//GEN-LAST:event_ordenarFechaActionPerformed

    private void radioEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEntradasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioEntradasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(variosReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(variosReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(variosReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(variosReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new variosReportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel labelEstadia;
    private javax.swing.JList<Cliente> listaClientesContratos;
    private javax.swing.JList<Empleado> listaEmpleadosMovs;
    private javax.swing.JList<Servicio> listaServiciosMasUtilizados;
    private javax.swing.JList<Vehiculo> listaVehiculos;
    private javax.swing.JButton ordenarFecha;
    private javax.swing.JRadioButton radioEntradas;
    private javax.swing.JRadioButton radioSalidas;
    private javax.swing.JRadioButton radioServicios;
    private javax.swing.ButtonGroup radiosHistorial;
    private javax.swing.JPanel tabEstadisticas;
    private javax.swing.JPanel tabHistorial;
    private javax.swing.JPanel tabMovimientos;
    // End of variables declaration//GEN-END:variables
}
